# Download Sentinel2/ECOSTRESS/Landsat

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import logging
import pandas as pd

In [3]:
from etdataset.api import download, search
from etdataset.provider import Collection, get_provider
from etdataset.logging import LoggerManager

/home/sarrazine/pyenvs/cesbio/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
logger = LoggerManager.get_logger()
LoggerManager.set_level(logging.INFO)  # INFO or DEBUG

### Donwload directory

In [5]:
output_dir = os.path.join(os.getcwd(), "download")
os.makedirs(output_dir, exist_ok=True)

### Product list

In [10]:
products = pd.read_csv("products.csv")

In [11]:
products

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,geometry
0,ECOv002_L2T_LSTE_26128_016_28PCA_20230213T1738...,2023-02-13,EarthData,ECOSTRESS,28PCA,NaN,NaN,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,NaN,"POLYGON ((-16.85552 -15.833756, -16.85552 13.4..."
1,ECOv002_L2T_LSTE_26372_016_28PCA_20230301T1116...,2023-03-01,EarthData,ECOSTRESS,28PCA,NaN,NaN,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,NaN,"POLYGON ((-16.85552 -15.833756, -16.85552 13.4..."
2,SENTINEL2A_20230328-114735-205_L2A_T28PCA_D,2023-03-28,THEIA,SENTINEL2,28PCA,0.0,80.0,https://theia.cnes.fr/atdistrib/resto2/collect...,e09e27d1cff4e8c103c3f55fde111dab,"POLYGON ((-16.855520248413 14.465514183044, -1..."
3,LC08_L2SP_204050_20230328_20230405_02_T1,2023-03-28,EarthExplorer,LANDSAT,NaN,0.0,NaN,LC08_L1TP_204050_20230328_20230405_02_T1,NaN,"POLYGON ((-16.18218 15.502, -14.05926 15.50316..."

In [12]:
download(products, output_dir=output_dir)

QUEUEING TASKS | : 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1868.08it/s]

File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_cloud.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_view_zenith.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_water.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_height.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST_err.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_QC.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_EmisWB.tif already downloaded

PROCESSING TASKS | : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 36472.21it/s]
COLLECTING RESULTS | : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 66576.25it/s]
QUEUEING TASKS | : 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 4006.57it/s]

File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_cloud.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_height.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_QC.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_water.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_EmisWB.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST_err.tif already downloaded

PROCESSING TASKS | : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 26426.76it/s]
COLLECTING RESULTS | : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 22175.32it/s]
24-02-06 09:30:50 :: INFO :: Download products: [['/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_water.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_cloud.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_view_zenith.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_height.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_QC.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST_err.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_EmisWB.tif'], ['/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_water.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_cloud.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_height.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_QC.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST_err.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_EmisWB.tif']]
24-02-06 09:30:55 :: INFO :: Product directory for LC08_L2SP_204050_20230328_20230405_02_T1 exists already. Skip product...
24-02-06 09:30:55 :: INFO :: Renew token
24-02-06 09:30:58 :: INFO :: Renew token
1.98GiB [15:29, 2.13MiB/s]

### Search and download Sentinel2 products

In [22]:
res = search(Collection.SENTINEL2, "2023-03-28", "2023-03-28", tile_id="28PCA")

24-02-06 09:52:26 :: INFO :: Renew token
24-02-06 09:52:29 :: INFO :: Number of products found: 1

In [23]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,geometry
0,SENTINEL2A_20230328-114735-205_L2A_T28PCA_D,2023-03-28,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,e09e27d1cff4e8c103c3f55fde111dab,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."

In [24]:
download(res, output_dir=output_dir)

24-02-06 09:52:52 :: INFO :: Renew token
24-02-06 09:52:59 :: INFO :: Archive /home/sarrazine/src/et-dataset/notebooks/download/SENTINEL2A_20230328-114735-205_L2A_T28PCA_D.zip already downloaded. Skipping.

### Search and download ECOSTRESS products

In [25]:
res = search(Collection.ECOSTRESS, "2023-02-13", "2023-03-01", tile_id="28PCA")

Granules found: 25

24-02-06 09:53:08 :: INFO :: Number of products found: 2

In [26]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,geometry
4,ECOv002_L2T_LSTE_26128_016_28PCA_20230213T1738...,2023-02-13,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
20,ECOv002_L2T_LSTE_26372_016_28PCA_20230301T1116...,2023-03-01,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."

In [27]:
download(res, output_dir=output_dir)

QUEUEING TASKS | : 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 4175.51it/s]

File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_water.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_cloud.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_view_zenith.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_height.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_QC.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST_err.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_EmisWB.tif already downloaded
File ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST.tif already downloaded

PROCESSING TASKS | : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 32577.12it/s]
COLLECTING RESULTS | : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 47393.27it/s]
QUEUEING TASKS | : 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 1091.78it/s]

File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_water.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_cloud.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_QC.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST_err.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_EmisWB.tif already downloaded
File ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_height.tif already downloaded

PROCESSING TASKS | : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 35288.62it/s]
COLLECTING RESULTS | : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 74518.09it/s]
24-02-06 09:53:10 :: INFO :: Download products: [['/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_water.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_cloud.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_view_zenith.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_height.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_QC.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_LST_err.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01/ECOv002_L2T_LSTE_26128_016_28PCA_20230213T173803_0710_01_EmisWB.tif'], ['/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_water.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_cloud.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_height.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_QC.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_LST_err.tif', '/home/sarrazine/src/et-dataset/notebooks/download/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01/ECOv002_L2T_LSTE_26372_016_28PCA_20230301T111607_0710_01_EmisWB.tif']]