# Search Sentinel2/ECOSTRESS/Landsat products

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import logging

In [3]:
from etdataset.api import search
from etdataset.provider import Collection
from etdataset.utils import get_bbox_from_roi
from etdataset.logging import LoggerManager
from etdataset.writer import write_results

/home/sarrazine/pyenvs/cesbio/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
logger = LoggerManager.get_logger()
LoggerManager.set_level(logging.DEBUG)  # INFO or DEBUG

### Search criteria

To be modified

In [5]:
# ROI
s2_tile_id = "28PCA"
data_path = os.environ["DATA_PATH"]
roi_path = os.path.join(data_path, "zones", "Zone_Senegal_Centre.shp")

In [6]:
# Acquisition dates
min_date_str = "2023-02-01"  # Format YYYY-MM-DD
max_date_str = "2023-03-31"  # Format YYYY-MM-DD

In [7]:
# Other criteria to filter products
max_cloud_cover = 20

In [8]:
output_dir = os.path.join(os.getcwd(), "out")
os.makedirs(output_dir, exist_ok=True)

### Prepare

In [9]:
roi_bbox, roi_crs = get_bbox_from_roi(roi_path)
print(roi_bbox)
print(roi_crs)

BoundingBox(left=-17.1, bottom=13.8, right=-15.9, top=15.0)
EPSG:4326

### Search Sentinel2 products

In [10]:
res = search(Collection.SENTINEL2, min_date_str, max_date_str, tile_id=s2_tile_id)

24-02-07 21:50:34 :: DEBUG :: Collection: Collection.SENTINEL2
24-02-07 21:50:34 :: DEBUG :: Provider: <class 'etdataset.provider.TheiaProvider'>
24-02-07 21:50:34 :: INFO :: Renew token
24-02-07 21:50:35 :: DEBUG :: Provider: TheiaProvider(name='THEIA', catalog=<theia_picker.download.TheiaCatalog object at 0x7f526e2431c0>, auth=<theia_picker.download.RequestsManager object at 0x7f526e242e60>)
24-02-07 21:50:35 :: DEBUG :: Search on THEIA catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20
24-02-07 21:50:38 :: DEBUG :: Number of products found on Theia: 12
24-02-07 21:50:38 :: DEBUG :: Number of products found on Theia after cloud cover filtering: 10
24-02-07 21:50:38 :: INFO :: Products found for SENTINEL2 in catalog: 10
24-02-07 21:50:38 :: DEBUG :: Number of products: 10
24-02-07 21:50:38 :: DEBUG :: Products found after filtering: 10
24-02-07 21:50:38 :: INFO :: Products found for SENTINEL2 after ROI filtering: 10

In [11]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,overlap_geometry,geometry,overlap_percentage
0,SENTINEL2A_20230328-114735-205_L2A_T28PCA_D,2023-03-28,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,e09e27d1cff4e8c103c3f55fde111dab,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
1,SENTINEL2B_20230323-114739-427_L2A_T28PCA_D,2023-03-23,THEIA,SENTINEL2,28PCA,12,80,https://theia.cnes.fr/atdistrib/resto2/collect...,55ecd31c7f95ac546df54dae7c49c179,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
2,SENTINEL2A_20230318-114735-293_L2A_T28PCA_D,2023-03-18,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,1ea5fc4e111821916417d332f8e1508a,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
3,SENTINEL2B_20230313-114741-580_L2A_T28PCA_D,2023-03-13,THEIA,SENTINEL2,28PCA,4,80,https://theia.cnes.fr/atdistrib/resto2/collect...,3acb908ed321b4fc737e6a12d1a4d0ab,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
4,SENTINEL2A_20230308-114732-624_L2A_T28PCA_D,2023-03-08,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,e9946922d2a1c4b9ca2bebc1e5acc91b,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
5,SENTINEL2B_20230303-114738-815_L2A_T28PCA_D,2023-03-03,THEIA,SENTINEL2,28PCA,12,80,https://theia.cnes.fr/atdistrib/resto2/collect...,18ba0c4e6569efaafadad69198b27145,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
6,SENTINEL2A_20230226-114734-900_L2A_T28PCA_D,2023-02-26,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,8e686b861ed93c83a92e53006213ace3,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
7,SENTINEL2B_20230221-114736-929_L2A_T28PCA_D,2023-02-21,THEIA,SENTINEL2,28PCA,1,80,https://theia.cnes.fr/atdistrib/resto2/collect...,34d5ec2f2089a15b2aebefc82285ccb9,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
8,SENTINEL2B_20230211-114735-878_L2A_T28PCA_D,2023-02-11,THEIA,SENTINEL2,28PCA,10,80,https://theia.cnes.fr/atdistrib/resto2/collect...,dd7fcc74745991be7426078552d36ffd,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0
9,SENTINEL2A_20230206-114736-226_L2A_T28PCA_D,2023-02-06,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,544366934f7ffb6ac186a4cf95be7156,"POLYGON ((-15.83696 14.47134, -15.83339 13.478...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",100.0

In [12]:
write_results(res, os.path.join(output_dir, "s2.csv"))

In [13]:
res = search(
    Collection.SENTINEL2, min_date_str, max_date_str, roi_bbox=roi_bbox, roi_crs=roi_crs
)

24-02-07 21:50:38 :: DEBUG :: Collection: Collection.SENTINEL2
24-02-07 21:50:38 :: DEBUG :: Provider: <class 'etdataset.provider.TheiaProvider'>
24-02-07 21:50:38 :: INFO :: Renew token
24-02-07 21:50:40 :: DEBUG :: Provider: TheiaProvider(name='THEIA', catalog=<theia_picker.download.TheiaCatalog object at 0x7f526e242e00>, auth=<theia_picker.download.RequestsManager object at 0x7f526e242530>)
24-02-07 21:50:40 :: DEBUG :: Search on THEIA catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = None, bbox = BoundingBox(left=-17.1, bottom=13.8, right=-15.9, top=15.0), max_cloud_cover = 20
24-02-07 21:50:42 :: DEBUG :: Number of products found on Theia: 118
24-02-07 21:50:42 :: DEBUG :: Number of products found on Theia after cloud cover filtering: 87
24-02-07 21:50:51 :: DEBUG :: Tiles to remove: [['28PCB' 37]
 ['28PDA' 37]
 ['28PDA' 80]
 ['28PDB' 37]
 ['28PDB' 80]]
24-02-07 21:50:51 :: DEBUG :: Tiles to keep: [['28PBA' 80]
 ['28PBB' 80]
 ['28PCA' 80]
 ['28PCB' 80]]
24-02-07 21:50:51 :: DEBUG :: Number of products found on Theia after tile filtering: 34
24-02-07 21:50:51 :: INFO :: Products found for SENTINEL2 in catalog: 34
24-02-07 21:50:51 :: DEBUG :: Number of products: 34
24-02-07 21:50:52 :: DEBUG :: Products found after filtering: 34
24-02-07 21:50:52 :: INFO :: Products found for SENTINEL2 after ROI filtering: 34

In [14]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,overlap_geometry,geometry,overlap_percentage
0,SENTINEL2A_20230328-114739-043_L2A_T28PBA_D,2023-03-28,THEIA,SENTINEL2,28PBA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,cad503bdcaef57a40d87b6bd0b96c741,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
1,SENTINEL2A_20230328-114735-205_L2A_T28PCA_D,2023-03-28,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,e09e27d1cff4e8c103c3f55fde111dab,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
2,SENTINEL2A_20230328-114724-521_L2A_T28PBB_D,2023-03-28,THEIA,SENTINEL2,28PBB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,214489680bcfda5179c984de30e114fa,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
3,SENTINEL2A_20230328-114720-999_L2A_T28PCB_D,2023-03-28,THEIA,SENTINEL2,28PCB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,999804996f06d512984d9f9123cbde33,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
4,SENTINEL2B_20230323-114743-256_L2A_T28PBA_D,2023-03-23,THEIA,SENTINEL2,28PBA,11,80,https://theia.cnes.fr/atdistrib/resto2/collect...,55d947c336ac6706bc1dddd00845eecc,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
5,SENTINEL2B_20230323-114739-427_L2A_T28PCA_D,2023-03-23,THEIA,SENTINEL2,28PCA,12,80,https://theia.cnes.fr/atdistrib/resto2/collect...,55ecd31c7f95ac546df54dae7c49c179,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
6,SENTINEL2B_20230323-114728-738_L2A_T28PBB_D,2023-03-23,THEIA,SENTINEL2,28PBB,2,80,https://theia.cnes.fr/atdistrib/resto2/collect...,79aaa0f95d3e9a27b4980df096e4368d,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
7,SENTINEL2B_20230323-114725-218_L2A_T28PCB_D,2023-03-23,THEIA,SENTINEL2,28PCB,17,80,https://theia.cnes.fr/atdistrib/resto2/collect...,c18eee25451b131e53ba8447cd351d00,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
8,SENTINEL2A_20230318-114739-129_L2A_T28PBA_D,2023-03-18,THEIA,SENTINEL2,28PBA,5,80,https://theia.cnes.fr/atdistrib/resto2/collect...,d82365b6a13ad8daa59a7f54add91757,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
9,SENTINEL2A_20230318-114735-293_L2A_T28PCA_D,2023-03-18,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,1ea5fc4e111821916417d332f8e1508a,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
10,SENTINEL2A_20230318-114724-618_L2A_T28PBB_D,2023-03-18,THEIA,SENTINEL2,28PBB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,f998e0c3260da0b624b70a34c9eecfb7,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
11,SENTINEL2A_20230318-114721-093_L2A_T28PCB_D,2023-03-18,THEIA,SENTINEL2,28PCB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,999c4860f3e18f969297d39924c253c2,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
12,SENTINEL2B_20230313-114745-430_L2A_T28PBA_D,2023-03-13,THEIA,SENTINEL2,28PBA,17,80,https://theia.cnes.fr/atdistrib/resto2/collect...,322efab57bc632c891f3298d8edf87f6,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
13,SENTINEL2B_20230313-114741-580_L2A_T28PCA_D,2023-03-13,THEIA,SENTINEL2,28PCA,4,80,https://theia.cnes.fr/atdistrib/resto2/collect...,3acb908ed321b4fc737e6a12d1a4d0ab,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
14,SENTINEL2B_20230313-114727-371_L2A_T28PCB_D,2023-03-13,THEIA,SENTINEL2,28PCB,8,80,https://theia.cnes.fr/atdistrib/resto2/collect...,5a5e14b8870c484b2587f654f13a6be4,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
15,SENTINEL2A_20230308-114736-445_L2A_T28PBA_D,2023-03-08,THEIA,SENTINEL2,28PBA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,7b833d88b5242e36352b4a89dc3cb960,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
16,SENTINEL2A_20230308-114732-624_L2A_T28PCA_D,2023-03-08,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,e9946922d2a1c4b9ca2bebc1e5acc91b,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
17,SENTINEL2A_20230308-114721-936_L2A_T28PBB_D,2023-03-08,THEIA,SENTINEL2,28PBB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,b8828f0dccfed23a29df409eea72517b,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
18,SENTINEL2A_20230308-114718-413_L2A_T28PCB_D,2023-03-08,THEIA,SENTINEL2,28PCB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,b1896965a3781da5e8df95577114608a,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
19,SENTINEL2B_20230303-114738-815_L2A_T28PCA_D,2023-03-03,THEIA,SENTINEL2,28PCA,12,80,https://theia.cnes.fr/atdistrib/resto2/collect...,18ba0c4e6569efaafadad69198b27145,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
20,SENTINEL2A_20230226-114738-734_L2A_T28PBA_D,2023-02-26,THEIA,SENTINEL2,28PBA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,1d6fccf08ecdc6dfc66dcb2278118152,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
21,SENTINEL2A_20230226-114734-900_L2A_T28PCA_D,2023-02-26,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,8e686b861ed93c83a92e53006213ace3,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
22,SENTINEL2A_20230226-114724-214_L2A_T28PBB_D,2023-02-26,THEIA,SENTINEL2,28PBB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,7e7b6622f62c0fc29d2cc77f29a18189,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
23,SENTINEL2A_20230226-114720-692_L2A_T28PCB_D,2023-02-26,THEIA,SENTINEL2,28PCB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,60b32d471aff13905d86c3447249a960,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
24,SENTINEL2B_20230221-114740-754_L2A_T28PBA_D,2023-02-21,THEIA,SENTINEL2,28PBA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,77f0a1be5d54017ffb49e91952456414,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
25,SENTINEL2B_20230221-114736-929_L2A_T28PCA_D,2023-02-21,THEIA,SENTINEL2,28PCA,1,80,https://theia.cnes.fr/atdistrib/resto2/collect...,34d5ec2f2089a15b2aebefc82285ccb9,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
26,SENTINEL2B_20230221-114726-243_L2A_T28PBB_D,2023-02-21,THEIA,SENTINEL2,28PBB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,cf2f73f68dce538c2690d60fcb54941e,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
27,SENTINEL2B_20230221-114722-722_L2A_T28PCB_D,2023-02-21,THEIA,SENTINEL2,28PCB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,612dcd8587206db44219ddb683247ef1,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
28,SENTINEL2B_20230211-114735-878_L2A_T28PCA_D,2023-02-11,THEIA,SENTINEL2,28PCA,10,80,https://theia.cnes.fr/atdistrib/resto2/collect...,dd7fcc74745991be7426078552d36ffd,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
29,SENTINEL2A_20230206-114740-067_L2A_T28PBA_D,2023-02-06,THEIA,SENTINEL2,28PBA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,b26662a92a114ddabf1177835cf30b6f,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251
30,SENTINEL2A_20230206-114736-226_L2A_T28PCA_D,2023-02-06,THEIA,SENTINEL2,28PCA,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,544366934f7ffb6ac186a4cf95be7156,"POLYGON ((-15.90000 14.47098, -15.90000 13.800...","POLYGON ((-16.85552 14.46551, -15.83696 14.471...",63.120630
31,SENTINEL2A_20230206-114725-551_L2A_T28PBB_D,2023-02-06,THEIA,SENTINEL2,28PBB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,35d2975c130c6dd549daefc80427251d,"POLYGON ((-16.76412 14.37783, -17.10000 14.374...","POLYGON ((-17.79446 15.35961, -16.77221 15.370...",20.551888
32,SENTINEL2A_20230206-114722-028_L2A_T28PCB_D,2023-02-06,THEIA,SENTINEL2,28PCB,0,80,https://theia.cnes.fr/atdistrib/resto2/collect...,7c6baac46ea263ae02c01efb24476016,"POLYGON ((-16.85479 14.37713, -16.86013 15.000...","POLYGON ((-16.86329 15.36934, -15.84047 15.375...",58.627817
33,SENTINEL2B_20230201-114738-121_L2A_T28PBA_D,2023-02-01,THEIA,SENTINEL2,28PBA,5,80,https://theia.cnes.fr/atdistrib/resto2/collect...,08b2d743b8e78bf1e2ab01fe60ddb158,"POLYGON ((-16.76482 14.46621, -16.75975 13.800...","POLYGON ((-17.78282 14.45638, -16.76482 14.466...",22.271251

### Search ECOSTRESSS products

In [15]:
res = search(Collection.ECOSTRESS, min_date_str, max_date_str, tile_id=s2_tile_id)

24-02-07 21:50:52 :: DEBUG :: Collection: Collection.ECOSTRESS
24-02-07 21:50:52 :: DEBUG :: Provider: <class 'etdataset.provider.EcostressProvider'>
24-02-07 21:50:58 :: DEBUG :: Provider: EcostressProvider(short_name='ECO_L2T_LSTE', doi='10.5067/ECOSTRESS/ECO_L2T_LSTE.002', collection='ECOSTRESS', name='EarthData', auth=<earthaccess.auth.Auth object at 0x7f526fb6e470>)
24-02-07 21:50:58 :: DEBUG :: Search on EarthData catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20

Granules found: 127

24-02-07 21:51:02 :: DEBUG :: Number of products found on EarthData: 127
24-02-07 21:51:02 :: DEBUG :: Number of products found on EarthData after tile filtering: 12
24-02-07 21:51:02 :: INFO :: Products found for ECOSTRESS in catalog: 12
24-02-07 21:51:02 :: DEBUG :: Number of products: 12
24-02-07 21:51:02 :: DEBUG :: Products found after filtering: 12
24-02-07 21:51:02 :: INFO :: Products found for ECOSTRESS after ROI filtering: 12

In [16]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,overlap_geometry,geometry,overlap_percentage
0,ECOv002_L2T_LSTE_26128_016_28PCA_20230213T1738...,2023-02-13,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
1,ECOv002_L2T_LSTE_26372_016_28PCA_20230301T1116...,2023-03-01,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
2,ECOv002_L2T_LSTE_26381_003_28PCA_20230302T0034...,2023-03-02,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
3,ECOv002_L2T_LSTE_26433_014_28PCA_20230305T0940...,2023-03-05,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
4,ECOv002_L2T_LSTE_26433_015_28PCA_20230305T0941...,2023-03-05,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
5,ECOv002_L2T_LSTE_26494_015_28PCA_20230309T0806...,2023-03-09,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
6,ECOv002_L2T_LSTE_26616_002_28PCA_20230317T0458...,2023-03-17,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
7,ECOv002_L2T_LSTE_26678_018_28PCA_20230321T0324...,2023-03-21,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
8,ECOv002_L2T_LSTE_26739_017_28PCA_20230325T0150...,2023-03-25,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
9,ECOv002_L2T_LSTE_26748_001_28PCA_20230325T1509...,2023-03-25,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
10,ECOv002_L2T_LSTE_26800_017_28PCA_20230329T0015...,2023-03-29,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0
11,ECOv002_L2T_LSTE_26809_001_28PCA_20230329T1333...,2023-03-29,EarthData,ECOSTRESS,28PCA,None,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.85552 14.47134, -15.83376 14.471...","POLYGON ((-16.85552 13.47358, -16.85552 14.471...",100.0

In [17]:
write_results(res, os.path.join(output_dir, "eco.csv"))

### Search HLS Landsat

In [18]:
res = search(Collection.HLSLANDSAT, min_date_str, max_date_str, tile_id=s2_tile_id)

24-02-07 21:51:02 :: DEBUG :: Collection: Collection.HLSLANDSAT
24-02-07 21:51:02 :: DEBUG :: Provider: <class 'etdataset.provider.HLSLProvider'>
24-02-07 21:51:05 :: DEBUG :: Provider: HLSLProvider(short_name='HLSL30', doi='10.5067/HLS/HLSL30.002', collection='HLSLANDSAT', name='EarthData', auth=<earthaccess.auth.Auth object at 0x7f526fb6e470>)
24-02-07 21:51:05 :: DEBUG :: Search on EarthData catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20

Granules found: 98

24-02-07 21:51:09 :: DEBUG :: Number of products found on EarthData: 98
24-02-07 21:51:09 :: DEBUG :: Number of products found on EarthData after tile filtering: 14
24-02-07 21:51:09 :: DEBUG :: Number of products found on EarthData after cloud cover filtering: 9
24-02-07 21:51:09 :: INFO :: Products found for HLSLANDSAT in catalog: 9
24-02-07 21:51:09 :: DEBUG :: Number of products: 9
24-02-07 21:51:09 :: DEBUG :: Products found after filtering: 9
24-02-07 21:51:09 :: INFO :: Products found for HLSLANDSAT after ROI filtering: 9

In [19]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,overlap_geometry,geometry,overlap_percentage
0,HLS.L30.T28PCA.2023054T112744.v2.0,2023-02-23,EarthData,HLSLANDSAT,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83607 14.231...","POLYGON ((-16.84759 13.47322, -16.00550 13.478...",100.0
1,HLS.L30.T28PCA.2023055T112121.v2.0,2023-02-24,EarthData,HLSLANDSAT,28PCA,1.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.20282 13.47714, -15.98699 14.470...","POLYGON ((-16.20282 13.47714, -15.83339 13.478...",100.0
2,HLS.L30.T28PCA.2023062T112730.v2.0,2023-03-03,EarthData,HLSLANDSAT,28PCA,17.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83605 14.224...","POLYGON ((-16.84759 13.47322, -16.00383 13.478...",100.0
3,HLS.L30.T28PCA.2023070T112736.v2.0,2023-03-11,EarthData,HLSLANDSAT,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83596 14.200...","POLYGON ((-16.84759 13.47322, -15.99829 13.478...",100.0
4,HLS.L30.T28PCA.2023071T112116.v2.0,2023-03-12,EarthData,HLSLANDSAT,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.21750 13.47707, -16.00202 14.470...","POLYGON ((-16.21750 13.47707, -15.83339 13.478...",100.0
5,HLS.L30.T28PCA.2023078T112722.v2.0,2023-03-19,EarthData,HLSLANDSAT,28PCA,7.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83610 14.237...","POLYGON ((-16.84759 13.47322, -16.00688 13.478...",100.0
6,HLS.L30.T28PCA.2023079T112124.v2.0,2023-03-20,EarthData,HLSLANDSAT,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.22332 13.47704, -16.00759 14.470...","POLYGON ((-16.22332 13.47704, -15.83339 13.478...",100.0
7,HLS.L30.T28PCA.2023086T112728.v2.0,2023-03-27,EarthData,HLSLANDSAT,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83587 14.176...","POLYGON ((-16.84759 13.47322, -15.99275 13.478...",100.0
8,HLS.L30.T28PCA.2023087T112106.v2.0,2023-03-28,EarthData,HLSLANDSAT,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.21667 13.47707, -16.00091 14.470...","POLYGON ((-16.21667 13.47707, -15.83339 13.478...",100.0

### Search HLS Sentinel2

In [20]:
res = search(Collection.HLSSENTINEL2, min_date_str, max_date_str, tile_id=s2_tile_id)

24-02-07 21:51:09 :: DEBUG :: Collection: Collection.HLSSENTINEL2
24-02-07 21:51:09 :: DEBUG :: Provider: <class 'etdataset.provider.HLSSProvider'>
24-02-07 21:51:11 :: DEBUG :: Provider: HLSSProvider(short_name='HLSS30', doi='10.5067/HLS/HLSS30.002', collection='HLSSENTINEL2', name='EarthData', auth=<earthaccess.auth.Auth object at 0x7f526fb6e470>)
24-02-07 21:51:11 :: DEBUG :: Search on EarthData catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20

Granules found: 168

24-02-07 21:51:17 :: DEBUG :: Number of products found on EarthData: 168
24-02-07 21:51:18 :: DEBUG :: Number of products found on EarthData after tile filtering: 24
24-02-07 21:51:18 :: DEBUG :: Number of products found on EarthData after cloud cover filtering: 20
24-02-07 21:51:18 :: INFO :: Products found for HLSSENTINEL2 in catalog: 20
24-02-07 21:51:18 :: DEBUG :: Number of products: 20
24-02-07 21:51:18 :: DEBUG :: Products found after filtering: 20
24-02-07 21:51:18 :: INFO :: Products found for HLSSENTINEL2 after ROI filtering: 20

In [21]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,overlap_geometry,geometry,overlap_percentage
0,HLS.S30.T28PCA.2023032T113319.v2.0,2023-02-01,EarthData,HLSSENTINEL2,28PCA,12.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83550 14.073...","POLYGON ((-16.84759 13.47322, -15.97584 13.478...",100.0
1,HLS.S30.T28PCA.2023037T113321.v2.0,2023-02-06,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83572 14.134...","POLYGON ((-16.84759 13.47322, -15.99025 13.478...",100.0
2,HLS.S30.T28PCA.2023042T113319.v2.0,2023-02-11,EarthData,HLSSENTINEL2,28PCA,5.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83566 14.118...","POLYGON ((-16.84759 13.47322, -15.98637 13.478...",100.0
3,HLS.S30.T28PCA.2023047T113321.v2.0,2023-02-16,EarthData,HLSSENTINEL2,28PCA,13.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83556 14.091...","POLYGON ((-16.84759 13.47322, -15.97972 13.478...",100.0
4,HLS.S30.T28PCA.2023052T113319.v2.0,2023-02-21,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83567 14.122...","POLYGON ((-16.84759 13.47322, -15.98776 13.478...",100.0
5,HLS.S30.T28PCA.2023054T112111.v2.0,2023-02-23,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.24522 13.47693, -16.02345 14.470...","POLYGON ((-16.24522 13.47693, -15.83339 13.478...",100.0
6,HLS.S30.T28PCA.2023057T113321.v2.0,2023-02-26,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83567 14.121...","POLYGON ((-16.84759 13.47322, -15.98693 13.478...",100.0
7,HLS.S30.T28PCA.2023059T112119.v2.0,2023-02-28,EarthData,HLSSENTINEL2,28PCA,1.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.24300 13.47694, -16.02122 14.470...","POLYGON ((-16.24300 13.47694, -15.83339 13.478...",100.0
8,HLS.S30.T28PCA.2023062T113319.v2.0,2023-03-03,EarthData,HLSSENTINEL2,28PCA,5.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83572 14.135...","POLYGON ((-16.84759 13.47322, -15.99081 13.478...",100.0
9,HLS.S30.T28PCA.2023064T112111.v2.0,2023-03-05,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.24411 13.47694, -16.02262 14.470...","POLYGON ((-16.24411 13.47694, -15.83339 13.478...",100.0
10,HLS.S30.T28PCA.2023067T113311.v2.0,2023-03-08,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83559 14.099...","POLYGON ((-16.84759 13.47322, -15.98194 13.478...",100.0
11,HLS.S30.T28PCA.2023069T112119.v2.0,2023-03-10,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.25408 13.47689, -16.03236 14.470...","POLYGON ((-16.25408 13.47689, -15.83339 13.478...",100.0
12,HLS.S30.T28PCA.2023072T113329.v2.0,2023-03-13,EarthData,HLSSENTINEL2,28PCA,1.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83588 14.178...","POLYGON ((-16.84759 13.47322, -16.00079 13.478...",100.0
13,HLS.S30.T28PCA.2023074T112111.v2.0,2023-03-15,EarthData,HLSSENTINEL2,28PCA,2.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.24633 13.47692, -16.02429 14.470...","POLYGON ((-16.24633 13.47692, -15.83339 13.478...",100.0
14,HLS.S30.T28PCA.2023077T113321.v2.0,2023-03-18,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83570 14.128...","POLYGON ((-16.84759 13.47322, -15.98915 13.478...",100.0
15,HLS.S30.T28PCA.2023079T112119.v2.0,2023-03-20,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.24799 13.47692, -16.02623 14.470...","POLYGON ((-16.24799 13.47692, -15.83339 13.478...",100.0
16,HLS.S30.T28PCA.2023082T113319.v2.0,2023-03-23,EarthData,HLSSENTINEL2,28PCA,7.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83572 14.135...","POLYGON ((-16.84759 13.47322, -15.99081 13.478...",100.0
17,HLS.S30.T28PCA.2023084T112111.v2.0,2023-03-25,EarthData,HLSSENTINEL2,28PCA,2.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.25020 13.47691, -16.02846 14.470...","POLYGON ((-16.25020 13.47691, -15.83339 13.478...",100.0
18,HLS.S30.T28PCA.2023087T113321.v2.0,2023-03-28,EarthData,HLSSENTINEL2,28PCA,1.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-15.83696 14.47134, -15.83569 14.126...","POLYGON ((-16.84759 13.47322, -15.98859 13.478...",100.0
19,HLS.S30.T28PCA.2023089T112119.v2.0,2023-03-30,EarthData,HLSSENTINEL2,28PCA,0.0,None,https://data.lpdaac.earthdatacloud.nasa.gov/lp...,None,"POLYGON ((-16.24937 13.47691, -16.02763 14.470...","POLYGON ((-16.24937 13.47691, -15.83339 13.478...",100.0

### Search Landsat products

In [22]:
res = search(Collection.LANDSAT, min_date_str, max_date_str, tile_id=s2_tile_id)

24-02-07 21:51:18 :: DEBUG :: Collection: Collection.LANDSAT
24-02-07 21:51:18 :: DEBUG :: Provider: <class 'etdataset.provider.LandsatProvider'>
24-02-07 21:51:22 :: DEBUG :: Provider: LandsatProvider(name='EarthExplorer', catalog=<landsatxplore.api.API object at 0x7f526e293910>, dataset='landsat_ot_c2_l2', collection='LANDSAT', auth=<landsatxplore.earthexplorer.EarthExplorer object at 0x7f52ec38b520>)
24-02-07 21:51:22 :: DEBUG :: Search on EarthExplorer catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20
24-02-07 21:51:24 :: DEBUG :: Number of products found on EarthExplorer: 25
24-02-07 21:51:24 :: DEBUG :: Number of products found on EarthData after cloud cover filtering: 24
24-02-07 21:51:24 :: INFO :: Products found for LANDSAT in catalog: 24
24-02-07 21:51:24 :: DEBUG :: Number of products: 24
24-02-07 21:51:24 :: DEBUG :: Products found after filtering: 24
24-02-07 21:51:24 :: INFO :: Products found for LANDSAT after ROI filtering: 24

In [23]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,Relative_orbit,URL,Checksum,overlap_geometry,geometry,overlap_percentage
0,LC08_L2SP_204050_20230328_20230405_02_T1,2023-03-28,EarthExplorer,LANDSAT,None,0,None,LC08_L1TP_204050_20230328_20230405_02_T1,None,"POLYGON ((-16.17676 14.47134, -15.83339 14.471...","POLYGON ((-16.18218 15.50200, -14.05926 15.503...",33.337261
1,LC08_L2SP_204051_20230328_20230405_02_T1,2023-03-28,EarthExplorer,LANDSAT,None,0,None,LC08_L1TP_204051_20230328_20230405_02_T1,None,"POLYGON ((-15.83339 14.05873, -15.83339 13.473...","POLYGON ((-16.49665 14.05752, -14.38498 14.061...",37.925959
2,LC09_L2SP_205050_20230327_20230329_02_T1,2023-03-27,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_205050_20230327_20230328_02_T1,None,"POLYGON ((-16.85552 14.47134, -15.83339 14.471...","POLYGON ((-17.73370 15.49638, -15.60047 15.512...",100.000000
3,LC09_L2SP_205051_20230327_20230329_02_T1,2023-03-27,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_205051_20230327_20230328_02_T1,None,"POLYGON ((-15.92718 14.07122, -15.92497 13.473...","POLYGON ((-18.04599 14.05379, -15.92718 14.071...",54.132121
4,LC09_L2SP_204050_20230320_20230322_02_T1,2023-03-20,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_204050_20230320_20230320_02_T1,None,"POLYGON ((-16.18789 14.47134, -15.83339 14.471...","POLYGON ((-16.19335 15.49923, -14.07046 15.500...",34.424073
5,LC09_L2SP_204051_20230320_20230322_02_T1,2023-03-20,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_204051_20230320_20230320_02_T1,None,"POLYGON ((-15.83339 14.05599, -15.83339 13.473...","POLYGON ((-16.50774 14.05473, -14.39610 14.058...",38.379293
6,LC08_L2SP_205050_20230319_20230324_02_T1,2023-03-19,EarthExplorer,LANDSAT,None,2,None,LC08_L1TP_205050_20230319_20230324_02_T1,None,"POLYGON ((-16.85552 14.47134, -15.83339 14.471...","POLYGON ((-17.73932 15.49902, -15.60607 15.515...",100.000000
7,LC08_L2SP_205051_20230319_20230324_02_T1,2023-03-19,EarthExplorer,LANDSAT,None,7,None,LC08_L1TP_205051_20230319_20230324_02_T1,None,"POLYGON ((-15.93274 14.07120, -15.93051 13.473...","POLYGON ((-18.05154 14.05372, -15.93274 14.071...",53.807985
8,LC08_L2SP_204050_20230312_20230321_02_T1,2023-03-12,EarthExplorer,LANDSAT,None,0,None,LC08_L1TP_204050_20230312_20230321_02_T1,None,"POLYGON ((-16.17676 14.47134, -15.83339 14.471...","POLYGON ((-16.18218 15.50200, -14.05926 15.503...",33.337261
9,LC08_L2SP_204051_20230312_20230321_02_T1,2023-03-12,EarthExplorer,LANDSAT,None,0,None,LC08_L1TP_204051_20230312_20230321_02_T1,None,"POLYGON ((-15.83339 14.05873, -15.83339 13.473...","POLYGON ((-16.49665 14.05752, -14.38498 14.061...",37.925959
10,LC09_L2SP_205050_20230311_20230313_02_T1,2023-03-11,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_205050_20230311_20230311_02_T1,None,"POLYGON ((-16.85552 14.47134, -15.83339 14.471...","POLYGON ((-17.73929 15.49632, -15.60607 15.512...",100.000000
11,LC09_L2SP_205051_20230311_20230313_02_T1,2023-03-11,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_205051_20230311_20230311_02_T1,None,"POLYGON ((-15.93274 14.07120, -15.93051 13.473...","POLYGON ((-18.05154 14.05372, -15.93274 14.071...",53.807986
12,LC09_L2SP_204050_20230304_20230412_02_T1,2023-03-04,EarthExplorer,LANDSAT,None,1,None,LC09_L1TP_204050_20230304_20230307_02_T1,None,"POLYGON ((-16.18789 14.47134, -15.83339 14.471...","POLYGON ((-16.19335 15.49923, -14.06766 15.500...",34.424073
13,LC09_L2SP_204051_20230304_20230308_02_T1,2023-03-04,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_204051_20230304_20230307_02_T1,None,"POLYGON ((-15.83339 14.05600, -15.83339 13.473...","POLYGON ((-16.50496 14.05475, -14.39610 14.058...",38.221885
14,LC08_L2SP_205050_20230303_20230316_02_T1,2023-03-03,EarthExplorer,LANDSAT,None,5,None,LC08_L1TP_205050_20230303_20230316_02_T1,None,"POLYGON ((-16.85552 14.47134, -15.83339 14.471...","POLYGON ((-17.73373 15.49909, -15.60328 15.515...",100.000000
15,LC08_L2SP_205051_20230303_20230316_02_T1,2023-03-03,EarthExplorer,LANDSAT,None,4,None,LC08_L1TP_205051_20230303_20230316_02_T1,None,"POLYGON ((-15.92718 14.07122, -15.92497 13.473...","POLYGON ((-18.04599 14.05379, -15.92718 14.071...",54.132120
16,LC08_L2SP_204050_20230224_20230301_02_T1,2023-02-24,EarthExplorer,LANDSAT,None,0,None,LC08_L1TP_204050_20230224_20230301_02_T1,None,"POLYGON ((-16.16284 14.47134, -15.83339 14.471...","POLYGON ((-16.16820 15.50207, -14.04528 15.503...",31.978339
17,LC08_L2SP_204051_20230224_20230301_02_T1,2023-02-24,EarthExplorer,LANDSAT,None,9,None,LC08_L1TP_204051_20230224_20230301_02_T1,None,"POLYGON ((-15.83339 14.05875, -15.83339 13.473...","POLYGON ((-16.48276 14.05760, -14.37109 14.061...",37.133664
18,LC09_L2SP_205050_20230223_20230308_02_T1,2023-02-23,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_205050_20230223_20230308_02_T1,None,"POLYGON ((-16.85552 14.47134, -15.83339 14.471...","POLYGON ((-17.74767 15.49621, -15.61446 15.512...",100.000000
19,LC09_L2SP_205051_20230223_20230308_02_T1,2023-02-23,EarthExplorer,LANDSAT,None,0,None,LC09_L1TP_205051_20230223_20230308_02_T1,None,"POLYGON ((-15.94107 14.07117, -15.93882 13.473...","POLYGON ((-18.05987 14.05361, -15.94107 14.071...",53.322266
20,LC09_L2SP_204050_20230216_20230310_02_T1,2023-02-16,EarthExplorer,LANDSAT,None,2,None,LC09_L1TP_204050_20230216_20230310_02_T1,None,"POLYGON ((-16.21573 14.47134, -15.83339 14.471...","POLYGON ((-16.22132 15.49907, -14.09843 15.500...",37.141359
21,LC08_L2SP_204050_20230208_20230217_02_T1,2023-02-08,EarthExplorer,LANDSAT,None,8,None,LC08_L1TP_204050_20230208_20230217_02_T1,None,"POLYGON ((-16.20460 14.47134, -15.83339 14.471...","POLYGON ((-16.21015 15.50185, -14.08723 15.503...",36.054862
22,LC08_L2SP_204051_20230208_20230217_02_T1,2023-02-08,EarthExplorer,LANDSAT,None,9,None,LC08_L1TP_204051_20230208_20230217_02_T1,None,"POLYGON ((-15.83339 14.05868, -15.83339 13.473...","POLYGON ((-16.52442 14.05734, -14.41277 14.061...",39.508579
23,LC09_L2SP_205051_20230207_20230311_02_T1,2023-02-07,EarthExplorer,LANDSAT,None,8,None,LC09_L1TP_205051_20230207_20230311_02_T1,None,"POLYGON ((-15.97997 14.07101, -15.97763 13.473...","POLYGON ((-18.10148 14.05308, -15.97997 14.071...",51.053350

In [24]:
write_results(res, os.path.join(output_dir, "ls.csv"))