# Search Sentinel2/ECOSTRESS/Landsat

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# import geopandas as gpd
# import pandas as pd
# import numpy as np
import os

# import rasterio as rio
import logging

# from datetime import datetime, timedelta
# from pyproj import CRS
# from rasterio.warp import transform_bounds
# from shapely.geometry import Polygon
# from tqdm import tqdm

In [3]:
from etdataset.api import search
from etdataset.provider import Collection, get_provider
from etdataset.utils import get_bbox_from_roi
from etdataset.logging import LoggerManager

/home/sarrazine/pyenvs/cesbio/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
logger = LoggerManager.get_logger()
LoggerManager.set_level(logging.DEBUG)  # INFO or DEBUG

### Search criteria

To be modified

In [5]:
# ROI
s2_tile_id = "28PCA"
data_path = os.environ["DATA_PATH"]
roi_path = os.path.join(data_path, "zones", "Zone_Senegal_Centre.shp")

In [6]:
# Acquisition dates
min_date_str = "2023-02-01"  # Format YYYY-MM-DD
max_date_str = "2023-03-31"  # Format YYYY-MM-DD

In [7]:
# Other criteria to filter products
max_cloud_cover = 20

### Prepare

In [8]:
roi_bbox, roi_crs = get_bbox_from_roi(roi_path)
print(roi_bbox)
print(roi_crs)

BoundingBox(left=-17.1, bottom=13.8, right=-15.9, top=15.0)
EPSG:4326

### Search Sentinel2 products

In [18]:
res = search(Collection.SENTINEL2, min_date_str, max_date_str, tile_id="28PCA")

24-02-01 15:15:18 :: DEBUG :: Collection: Collection.SENTINEL2
24-02-01 15:15:18 :: INFO :: Renew token
24-02-01 15:15:21 :: DEBUG :: Provider: TheiaProvider(catalog=<theia_picker.download.TheiaCatalog object at 0x7f458ca18a90>, auth=<theia_picker.download.RequestsManager object at 0x7f458ca187c0>)
24-02-01 15:15:21 :: DEBUG :: Number of products found for 28PCA: 12
24-02-01 15:15:21 :: DEBUG :: Number of products found for 28PCA after cloud cover filtering: 10
24-02-01 15:15:21 :: DEBUG :: Number of products found on THEIA: 10
24-02-01 15:15:21 :: INFO :: Number of products found: 10

In [19]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,URL,Checksum,geometry
0,SENTINEL2A_20230328-114735-205_L2A_T28PCA_D,2023-03-28,THEIA,SENTINEL2,28PCA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,e09e27d1cff4e8c103c3f55fde111dab,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
1,SENTINEL2B_20230323-114739-427_L2A_T28PCA_D,2023-03-23,THEIA,SENTINEL2,28PCA,12,https://theia.cnes.fr/atdistrib/resto2/collect...,55ecd31c7f95ac546df54dae7c49c179,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
2,SENTINEL2A_20230318-114735-293_L2A_T28PCA_D,2023-03-18,THEIA,SENTINEL2,28PCA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,1ea5fc4e111821916417d332f8e1508a,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
3,SENTINEL2B_20230313-114741-580_L2A_T28PCA_D,2023-03-13,THEIA,SENTINEL2,28PCA,4,https://theia.cnes.fr/atdistrib/resto2/collect...,3acb908ed321b4fc737e6a12d1a4d0ab,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
4,SENTINEL2A_20230308-114732-624_L2A_T28PCA_D,2023-03-08,THEIA,SENTINEL2,28PCA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,e9946922d2a1c4b9ca2bebc1e5acc91b,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
5,SENTINEL2B_20230303-114738-815_L2A_T28PCA_D,2023-03-03,THEIA,SENTINEL2,28PCA,12,https://theia.cnes.fr/atdistrib/resto2/collect...,18ba0c4e6569efaafadad69198b27145,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
6,SENTINEL2A_20230226-114734-900_L2A_T28PCA_D,2023-02-26,THEIA,SENTINEL2,28PCA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,8e686b861ed93c83a92e53006213ace3,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
7,SENTINEL2B_20230221-114736-929_L2A_T28PCA_D,2023-02-21,THEIA,SENTINEL2,28PCA,1,https://theia.cnes.fr/atdistrib/resto2/collect...,34d5ec2f2089a15b2aebefc82285ccb9,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
8,SENTINEL2B_20230211-114735-878_L2A_T28PCA_D,2023-02-11,THEIA,SENTINEL2,28PCA,10,https://theia.cnes.fr/atdistrib/resto2/collect...,dd7fcc74745991be7426078552d36ffd,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
9,SENTINEL2A_20230206-114736-226_L2A_T28PCA_D,2023-02-06,THEIA,SENTINEL2,28PCA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,544366934f7ffb6ac186a4cf95be7156,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."

In [20]:
res = search(
    Collection.SENTINEL2, min_date_str, max_date_str, roi_bbox=roi_bbox, roi_crs=roi_crs
)

24-02-01 15:15:51 :: DEBUG :: Collection: Collection.SENTINEL2
24-02-01 15:15:51 :: INFO :: Renew token
24-02-01 15:15:53 :: DEBUG :: Provider: TheiaProvider(catalog=<theia_picker.download.TheiaCatalog object at 0x7f458c523310>, auth=<theia_picker.download.RequestsManager object at 0x7f458c523460>)
24-02-01 15:15:55 :: DEBUG :: Number of products found for None: 118
24-02-01 15:15:55 :: DEBUG :: Number of products found for None after cloud cover filtering: 87
24-02-01 15:15:55 :: DEBUG :: Number of products found on THEIA: 87
24-02-01 15:15:55 :: INFO :: Number of products found: 87

In [21]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,URL,Checksum,geometry
0,SENTINEL2B_20230330-113745-671_L2A_T28PCA_D,2023-03-30,THEIA,SENTINEL2,28PCA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,4c96e006c0737ebaf7c6d5a88e681cfb,"POLYGON ((-16.85552 14.46551, -15.83696 14.471..."
1,SENTINEL2B_20230330-113742-355_L2A_T28PDA_D,2023-03-30,THEIA,SENTINEL2,28PDA,2,https://theia.cnes.fr/atdistrib/resto2/collect...,c3ed4e28c3783714dc59e6f1b790bc3b,"POLYGON ((-15.92826 14.47100, -14.90943 14.472..."
2,SENTINEL2B_20230330-113733-106_L2A_T28PCB_D,2023-03-30,THEIA,SENTINEL2,28PCB,3,https://theia.cnes.fr/atdistrib/resto2/collect...,46c7f3ecfdc79447cd0263871049415f,"POLYGON ((-16.86329 15.36934, -15.84047 15.375..."
3,SENTINEL2B_20230330-113727-916_L2A_T28PDB_D,2023-03-30,THEIA,SENTINEL2,28PDB,4,https://theia.cnes.fr/atdistrib/resto2/collect...,d531deaedb8e16bb0d6246fd976eb565,"POLYGON ((-15.93215 15.37519, -14.90905 15.377..."
4,SENTINEL2A_20230328-114739-043_L2A_T28PBA_D,2023-03-28,THEIA,SENTINEL2,28PBA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,cad503bdcaef57a40d87b6bd0b96c741,"POLYGON ((-17.78282 14.45638, -16.76482 14.466..."
...,...,...,...,...,...,...,...,...,...
82,SENTINEL2A_20230206-114722-028_L2A_T28PCB_D,2023-02-06,THEIA,SENTINEL2,28PCB,0,https://theia.cnes.fr/atdistrib/resto2/collect...,7c6baac46ea263ae02c01efb24476016,"POLYGON ((-16.86329 15.36934, -15.84047 15.375..."
83,SENTINEL2A_20230206-114717-809_L2A_T28PDB_D,2023-02-06,THEIA,SENTINEL2,28PDB,0,https://theia.cnes.fr/atdistrib/resto2/collect...,aaef0002bea982fc136789abb399d8e4,"POLYGON ((-15.93215 15.37519, -14.90905 15.377..."
84,SENTINEL2B_20230201-114738-121_L2A_T28PBA_D,2023-02-01,THEIA,SENTINEL2,28PBA,5,https://theia.cnes.fr/atdistrib/resto2/collect...,08b2d743b8e78bf1e2ab01fe60ddb158,"POLYGON ((-17.78282 14.45638, -16.76482 14.466..."
85,SENTINEL2B_20230201-114727-757_L2A_T28PDA_D,2023-02-01,THEIA,SENTINEL2,28PDA,0,https://theia.cnes.fr/atdistrib/resto2/collect...,0f0b358264647aff2bdc8388227cea5e,"POLYGON ((-15.92826 14.47100, -14.90943 14.472..."
86,SENTINEL2B_20230201-114715-983_L2A_T28PDB_D,2023-02-01,THEIA,SENTINEL2,28PDB,9,https://theia.cnes.fr/atdistrib/resto2/collect...,1a3cbba337d74e923b0f9dc54c170164,"POLYGON ((-15.93215 15.37519, -14.90905 15.377..."

### Search ECOSTRESSS products

In [51]:
res = search(Collection.ECOSTRESS, min_date_str, max_date_str, tile_id="28PCA")

24-02-01 18:49:21 :: DEBUG :: Collection: Collection.ECOSTRESS
24-02-01 18:49:21 :: DEBUG :: Provider: <class 'etdataset.provider.EcostressProvider'>
24-02-01 18:49:23 :: DEBUG :: Provider: EcostressProvider(short_name='ECO_L2T_LSTE', doi='10.5067/ECOSTRESS/ECO_L2T_LSTE.002', collection='Ecostress', name='EarthData', auth=<earthaccess.auth.Auth object at 0x7fcc44b08790>)
24-02-01 18:49:23 :: DEBUG :: Search on EarthData catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20

Granules found: 127

24-02-01 18:49:26 :: DEBUG :: Number of products found on EarthData: 127
24-02-01 18:49:26 :: DEBUG :: Number of products found on EarthData after tile filtering: 12
24-02-01 18:49:26 :: INFO :: Number of products found: 12

In [52]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,URL,Checksum,geometry
7,ECOv002_L2T_LSTE_26128_016_28PCA_20230213T1738...,2023-02-13,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
23,ECOv002_L2T_LSTE_26372_016_28PCA_20230301T1116...,2023-03-01,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
34,ECOv002_L2T_LSTE_26381_003_28PCA_20230302T0034...,2023-03-02,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
41,ECOv002_L2T_LSTE_26433_014_28PCA_20230305T0940...,2023-03-05,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
46,ECOv002_L2T_LSTE_26433_015_28PCA_20230305T0941...,2023-03-05,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
61,ECOv002_L2T_LSTE_26494_015_28PCA_20230309T0806...,2023-03-09,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
69,ECOv002_L2T_LSTE_26616_002_28PCA_20230317T0458...,2023-03-17,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
83,ECOv002_L2T_LSTE_26678_018_28PCA_20230321T0324...,2023-03-21,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
88,ECOv002_L2T_LSTE_26739_017_28PCA_20230325T0150...,2023-03-25,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
107,ECOv002_L2T_LSTE_26748_001_28PCA_20230325T1509...,2023-03-25,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
116,ECOv002_L2T_LSTE_26800_017_28PCA_20230329T0015...,2023-03-29,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."
122,ECOv002_L2T_LSTE_26809_001_28PCA_20230329T1333...,2023-03-29,EarthData,Ecostress,28PCA,None,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.85552 -15.83376, -16.85552 13.47..."

### Search HLS Landsat

In [21]:
res = search(Collection.HLSL, min_date_str, max_date_str, tile_id="28PCA")

24-02-01 22:44:56 :: DEBUG :: Collection: Collection.HLSL
24-02-01 22:44:56 :: DEBUG :: Provider: <class 'etdataset.provider.HLSLProvider'>
24-02-01 22:45:02 :: DEBUG :: Provider: HLSLProvider(short_name='HLSL30', doi='10.5067/HLS/HLSL30.002', collection='HLSLandsat', name='EarthData', auth=<earthaccess.auth.Auth object at 0x7f5ae434a050>)
24-02-01 22:45:02 :: DEBUG :: Search on EarthData catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20

Granules found: 98

24-02-01 22:45:07 :: DEBUG :: Number of products found on EarthData: 98
24-02-01 22:45:07 :: DEBUG :: Number of products found on EarthData after tile filtering: 14
24-02-01 22:45:07 :: DEBUG :: Number of products found on EarthData after cloud cover filtering: 9
24-02-01 22:45:07 :: INFO :: Number of products found: 9

In [22]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,URL,Checksum,geometry
32,HLS.L30.T28PCA.2023054T112744.v2.0,2023-02-23,EarthData,HLSLandsat,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -16.00550 13.478..."
38,HLS.L30.T28PCA.2023055T112121.v2.0,2023-02-24,EarthData,HLSLandsat,28PCA,1.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.20282 13.47714, -15.83339 13.478..."
46,HLS.L30.T28PCA.2023062T112730.v2.0,2023-03-03,EarthData,HLSLandsat,28PCA,17.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -16.00383 13.478..."
60,HLS.L30.T28PCA.2023070T112736.v2.0,2023-03-11,EarthData,HLSLandsat,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.99829 13.478..."
66,HLS.L30.T28PCA.2023071T112116.v2.0,2023-03-12,EarthData,HLSLandsat,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.21750 13.47707, -15.83339 13.478..."
74,HLS.L30.T28PCA.2023078T112722.v2.0,2023-03-19,EarthData,HLSLandsat,28PCA,7.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -16.00688 13.478..."
81,HLS.L30.T28PCA.2023079T112124.v2.0,2023-03-20,EarthData,HLSLandsat,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.22332 13.47704, -15.83339 13.478..."
88,HLS.L30.T28PCA.2023086T112728.v2.0,2023-03-27,EarthData,HLSLandsat,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.99275 13.478..."
95,HLS.L30.T28PCA.2023087T112106.v2.0,2023-03-28,EarthData,HLSLandsat,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.21667 13.47707, -15.83339 13.478..."

### Search HLS Sentinel2

In [23]:
res = search(Collection.HLSS, min_date_str, max_date_str, tile_id="28PCA")

24-02-01 22:45:11 :: DEBUG :: Collection: Collection.HLSS
24-02-01 22:45:11 :: DEBUG :: Provider: <class 'etdataset.provider.HLSSProvider'>
24-02-01 22:45:13 :: DEBUG :: Provider: HLSSProvider(short_name='HLSS30', doi='10.5067/HLS/HLSS30.002', collection='HLSSentinel2', name='EarthData', auth=<earthaccess.auth.Auth object at 0x7f5ae434a050>)
24-02-01 22:45:13 :: DEBUG :: Search on EarthData catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20

Granules found: 168

24-02-01 22:45:18 :: DEBUG :: Number of products found on EarthData: 168
24-02-01 22:45:18 :: DEBUG :: Number of products found on EarthData after tile filtering: 24
24-02-01 22:45:18 :: DEBUG :: Number of products found on EarthData after cloud cover filtering: 20
24-02-01 22:45:18 :: INFO :: Number of products found: 20

In [24]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,URL,Checksum,geometry
4,HLS.S30.T28PCA.2023032T113319.v2.0,2023-02-01,EarthData,HLSSentinel2,28PCA,12.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.97584 13.478..."
18,HLS.S30.T28PCA.2023037T113321.v2.0,2023-02-06,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.99025 13.478..."
32,HLS.S30.T28PCA.2023042T113319.v2.0,2023-02-11,EarthData,HLSSentinel2,28PCA,5.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.98637 13.478..."
46,HLS.S30.T28PCA.2023047T113321.v2.0,2023-02-16,EarthData,HLSSentinel2,28PCA,13.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.97972 13.478..."
60,HLS.S30.T28PCA.2023052T113319.v2.0,2023-02-21,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.98776 13.478..."
67,HLS.S30.T28PCA.2023054T112111.v2.0,2023-02-23,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.24522 13.47693, -15.83339 13.478..."
74,HLS.S30.T28PCA.2023057T113321.v2.0,2023-02-26,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.98693 13.478..."
81,HLS.S30.T28PCA.2023059T112119.v2.0,2023-02-28,EarthData,HLSSentinel2,28PCA,1.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.24300 13.47694, -15.83339 13.478..."
88,HLS.S30.T28PCA.2023062T113319.v2.0,2023-03-03,EarthData,HLSSentinel2,28PCA,5.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.99081 13.478..."
95,HLS.S30.T28PCA.2023064T112111.v2.0,2023-03-05,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.24411 13.47694, -15.83339 13.478..."
102,HLS.S30.T28PCA.2023067T113311.v2.0,2023-03-08,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.98194 13.478..."
109,HLS.S30.T28PCA.2023069T112119.v2.0,2023-03-10,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.25408 13.47689, -15.83339 13.478..."
116,HLS.S30.T28PCA.2023072T113329.v2.0,2023-03-13,EarthData,HLSSentinel2,28PCA,1.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -16.00079 13.478..."
123,HLS.S30.T28PCA.2023074T112111.v2.0,2023-03-15,EarthData,HLSSentinel2,28PCA,2.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.24633 13.47692, -15.83339 13.478..."
130,HLS.S30.T28PCA.2023077T113321.v2.0,2023-03-18,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.98915 13.478..."
137,HLS.S30.T28PCA.2023079T112119.v2.0,2023-03-20,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.24799 13.47692, -15.83339 13.478..."
144,HLS.S30.T28PCA.2023082T113319.v2.0,2023-03-23,EarthData,HLSSentinel2,28PCA,7.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.99081 13.478..."
151,HLS.S30.T28PCA.2023084T112111.v2.0,2023-03-25,EarthData,HLSSentinel2,28PCA,2.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.25020 13.47691, -15.83339 13.478..."
158,HLS.S30.T28PCA.2023087T113321.v2.0,2023-03-28,EarthData,HLSSentinel2,28PCA,1.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.84759 13.47322, -15.98859 13.478..."
165,HLS.S30.T28PCA.2023089T112119.v2.0,2023-03-30,EarthData,HLSSentinel2,28PCA,0.0,[https://data.lpdaac.earthdatacloud.nasa.gov/l...,None,"POLYGON ((-16.24937 13.47691, -15.83339 13.478..."

### Search Landsat products

In [25]:
res = search(Collection.LANDSAT, min_date_str, max_date_str, tile_id="28PCA")

24-02-01 22:45:18 :: DEBUG :: Collection: Collection.LANDSAT
24-02-01 22:45:18 :: DEBUG :: Provider: <class 'etdataset.provider.LandsatProvider'>
24-02-01 22:45:19 :: DEBUG :: Provider: LandsatProvider(name='EarthExplorer', catalog=<landsatxplore.api.API object at 0x7f5ab3384dc0>)
24-02-01 22:45:19 :: DEBUG :: Search on EarthExplorer catalog: min_date=2023-02-01, max_date = 2023-03-31, tile_id = 28PCA, bbox = None, max_cloud_cover = 20
24-02-01 22:45:21 :: DEBUG :: Number of products found on EarthExplorer: 25
24-02-01 22:45:21 :: DEBUG :: Number of products found on EarthData after cloud cover filtering: 24
24-02-01 22:45:21 :: INFO :: Number of products found: 24

In [26]:
res

,Product_name,Date,Provider,Collection,Tile_ID,Cloud_cover,URL,Checksum,geometry
0,LC08_L2SP_204050_20230328_20230405_02_T1,2023-03-28,EarthExplorer,Landsat,None,0,LC08_L1TP_204050_20230328_20230405_02_T1,None,"POLYGON ((-16.18218 15.50200, -14.05926 15.503..."
1,LC08_L2SP_204051_20230328_20230405_02_T1,2023-03-28,EarthExplorer,Landsat,None,0,LC08_L1TP_204051_20230328_20230405_02_T1,None,"POLYGON ((-16.49665 14.05752, -14.38498 14.061..."
2,LC09_L2SP_205050_20230327_20230329_02_T1,2023-03-27,EarthExplorer,Landsat,None,0,LC09_L1TP_205050_20230327_20230328_02_T1,None,"POLYGON ((-17.73370 15.49638, -15.60047 15.512..."
3,LC09_L2SP_205051_20230327_20230329_02_T1,2023-03-27,EarthExplorer,Landsat,None,0,LC09_L1TP_205051_20230327_20230328_02_T1,None,"POLYGON ((-18.04599 14.05379, -15.92718 14.071..."
4,LC09_L2SP_204050_20230320_20230322_02_T1,2023-03-20,EarthExplorer,Landsat,None,0,LC09_L1TP_204050_20230320_20230320_02_T1,None,"POLYGON ((-16.19335 15.49923, -14.07046 15.500..."
5,LC09_L2SP_204051_20230320_20230322_02_T1,2023-03-20,EarthExplorer,Landsat,None,0,LC09_L1TP_204051_20230320_20230320_02_T1,None,"POLYGON ((-16.50774 14.05473, -14.39610 14.058..."
6,LC08_L2SP_205050_20230319_20230324_02_T1,2023-03-19,EarthExplorer,Landsat,None,2,LC08_L1TP_205050_20230319_20230324_02_T1,None,"POLYGON ((-17.73932 15.49902, -15.60607 15.515..."
7,LC08_L2SP_205051_20230319_20230324_02_T1,2023-03-19,EarthExplorer,Landsat,None,7,LC08_L1TP_205051_20230319_20230324_02_T1,None,"POLYGON ((-18.05154 14.05372, -15.93274 14.071..."
8,LC08_L2SP_204050_20230312_20230321_02_T1,2023-03-12,EarthExplorer,Landsat,None,0,LC08_L1TP_204050_20230312_20230321_02_T1,None,"POLYGON ((-16.18218 15.50200, -14.05926 15.503..."
9,LC08_L2SP_204051_20230312_20230321_02_T1,2023-03-12,EarthExplorer,Landsat,None,0,LC08_L1TP_204051_20230312_20230321_02_T1,None,"POLYGON ((-16.49665 14.05752, -14.38498 14.061..."
10,LC09_L2SP_205050_20230311_20230313_02_T1,2023-03-11,EarthExplorer,Landsat,None,0,LC09_L1TP_205050_20230311_20230311_02_T1,None,"POLYGON ((-17.73929 15.49632, -15.60607 15.512..."
11,LC09_L2SP_205051_20230311_20230313_02_T1,2023-03-11,EarthExplorer,Landsat,None,0,LC09_L1TP_205051_20230311_20230311_02_T1,None,"POLYGON ((-18.05154 14.05372, -15.93274 14.071..."
12,LC09_L2SP_204050_20230304_20230412_02_T1,2023-03-04,EarthExplorer,Landsat,None,1,LC09_L1TP_204050_20230304_20230307_02_T1,None,"POLYGON ((-16.19335 15.49923, -14.06766 15.500..."
13,LC09_L2SP_204051_20230304_20230308_02_T1,2023-03-04,EarthExplorer,Landsat,None,0,LC09_L1TP_204051_20230304_20230307_02_T1,None,"POLYGON ((-16.50496 14.05475, -14.39610 14.058..."
14,LC08_L2SP_205050_20230303_20230316_02_T1,2023-03-03,EarthExplorer,Landsat,None,5,LC08_L1TP_205050_20230303_20230316_02_T1,None,"POLYGON ((-17.73373 15.49909, -15.60328 15.515..."
15,LC08_L2SP_205051_20230303_20230316_02_T1,2023-03-03,EarthExplorer,Landsat,None,4,LC08_L1TP_205051_20230303_20230316_02_T1,None,"POLYGON ((-18.04599 14.05379, -15.92718 14.071..."
16,LC08_L2SP_204050_20230224_20230301_02_T1,2023-02-24,EarthExplorer,Landsat,None,0,LC08_L1TP_204050_20230224_20230301_02_T1,None,"POLYGON ((-16.16820 15.50207, -14.04528 15.503..."
17,LC08_L2SP_204051_20230224_20230301_02_T1,2023-02-24,EarthExplorer,Landsat,None,9,LC08_L1TP_204051_20230224_20230301_02_T1,None,"POLYGON ((-16.48276 14.05760, -14.37109 14.061..."
18,LC09_L2SP_205050_20230223_20230308_02_T1,2023-02-23,EarthExplorer,Landsat,None,0,LC09_L1TP_205050_20230223_20230308_02_T1,None,"POLYGON ((-17.74767 15.49621, -15.61446 15.512..."
19,LC09_L2SP_205051_20230223_20230308_02_T1,2023-02-23,EarthExplorer,Landsat,None,0,LC09_L1TP_205051_20230223_20230308_02_T1,None,"POLYGON ((-18.05987 14.05361, -15.94107 14.071..."
20,LC09_L2SP_204050_20230216_20230310_02_T1,2023-02-16,EarthExplorer,Landsat,None,2,LC09_L1TP_204050_20230216_20230310_02_T1,None,"POLYGON ((-16.22132 15.49907, -14.09843 15.500..."
22,LC08_L2SP_204050_20230208_20230217_02_T1,2023-02-08,EarthExplorer,Landsat,None,8,LC08_L1TP_204050_20230208_20230217_02_T1,None,"POLYGON ((-16.21015 15.50185, -14.08723 15.503..."
23,LC08_L2SP_204051_20230208_20230217_02_T1,2023-02-08,EarthExplorer,Landsat,None,9,LC08_L1TP_204051_20230208_20230217_02_T1,None,"POLYGON ((-16.52442 14.05734, -14.41277 14.061..."
24,LC09_L2SP_205051_20230207_20230311_02_T1,2023-02-07,EarthExplorer,Landsat,None,8,LC09_L1TP_205051_20230207_20230311_02_T1,None,"POLYGON ((-18.10148 14.05308, -15.97997 14.071..."